# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45e13db4ebd739c676eccda385a6c39183d7abd747cd2283d8eb4c80c36f42b60577f0e4e4f7c717687343560c9e74f2725d08311b4393422f15157a2682e118

test:
  secret_key_base: 540bb2f007126fb150573a80e7ba9227f0f3e00ccd6cc347b92d9da7e599e4fd8199e5baad9754edf417b42836ac027a470905a50a6f4f01dc63b2173735ee72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
